"""Your migration message

Revision ID: d5d04e3e6a6a
Revises: 
Create Date: 2024-12-11 13:37:52.995952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d04e3e6a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcast_history', sa.Column('success_count', sa.Integer(), nullable=True))
    op.add_column('broadcast_history', sa.Column('failed_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcast_history', 'failed_count')
    op.drop_column('broadcast_history', 'success_count')
    # ### end Alembic commands ###
